# Generated by Django 2.2.9 on 2022-04-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220420_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
