# Generated by Django 2.2.9 on 2022-04-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
